import {defaultSettings,validateSettings,dateKey,activeSchedule} from './focus-core.mjs';
import {makeRules} from './rules.mjs';
let queue=Promise.resolve();const serial=fn=>{const task=queue.then(fn);queue=task.catch(()=>{});return task;};
async function state(){const s=await chrome.storage.local.get(['config','activeUntil','day','usage','blocked','lastTick','trackedDomain','enabled']);return {config:defaultSettings(),activeUntil:0,day:dateKey(),usage:{},blocked:0,lastTick:Date.now(),trackedDomain:null,enabled:true,...s};}
function active(s){return s.enabled&&(s.activeUntil>Date.now()||s.config.autoBlock&&!!activeSchedule(s.config.schedules));}
async function apply(s){const day=dateKey();if(s.day!==day){s.day=day;s.usage={};s.blocked=0;}const rules=s.enabled?makeRules(s.config,active(s),s.usage):[];const old=await chrome.declarativeNetRequest.getDynamicRules();if(JSON.stringify(old)!==JSON.stringify(rules))await chrome.declarativeNetRequest.updateDynamicRules({removeRuleIds:old.map(r=>r.id),addRules:rules});await chrome.storage.local.set(s);await chrome.action.setBadgeText({text:active(s)?'ON':!s.enabled?'OFF':''});await chrome.action.setBadgeBackgroundColor({color:'#123b32'});return s;}
async function tick(){const s=await state(),now=Date.now(),window=await chrome.windows.getLastFocused(),idle=await chrome.idle.queryState(60);if(s.day!==dateKey()){s.day=dateKey();s.usage={};s.blocked=0;s.trackedDomain=null;}if(s.trackedDomain&&window.focused&&idle==='active'){s.usage[s.trackedDomain]=(s.usage[s.trackedDomain]||0)+Math.max(0,Math.min(32,(now-s.lastTick)/1000));}const tabs=window.focused?await chrome.tabs.query({active:true,windowId:window.id}):[];let host='';try{host=new URL(tabs[0]?.url||'').hostname;}catch{}s.trackedDomain=s.config.limits.find(x=>host===x.domain||host.endsWith('.'+x.domain))?.domain||null;s.lastTick=now;await apply(s);}
chrome.runtime.onInstalled.addListener(()=>{chrome.alarms.create('rebound-check',{periodInMinutes:.5});serial(()=>apply({config:defaultSettings(),activeUntil:0,day:dateKey(),usage:{},blocked:0,enabled:true,lastTick:Date.now(),trackedDomain:null}));});chrome.runtime.onStartup.addListener(()=>{chrome.alarms.create('rebound-check',{periodInMinutes:.5});serial(tick);});chrome.alarms.onAlarm.addListener(a=>{if(a.name==='rebound-check')serial(tick);});chrome.tabs.onActivated.addListener(()=>serial(tick));chrome.windows.onFocusChanged.addListener(()=>serial(tick));chrome.tabs.onUpdated.addListener((id,change)=>{if(change.url)serial(tick);});
chrome.runtime.onMessage.addListener((m,sender,reply)=>{serial(async()=>{const s=await state();if(m.type==='sync-guard'){const origin=new URL(sender.url||'https://invalid').origin;if(!['https://rebound-school-comeback.astrapro70.chatgpt.site','http://127.0.0.1:4173'].includes(origin))throw Error('Untrusted sender');s.config=validateSettings(m.config);s.activeUntil=Number.isFinite(m.activeUntil)?Math.max(0,Math.min(m.activeUntil,Date.now()+43200000)):0;await apply(s);}else if(m.type==='toggle'&&sender.url?.startsWith(chrome.runtime.getURL('popup.html'))){s.enabled=!s.enabled;await apply(s);}else if(m.type==='feed-block'){s.blocked++;await chrome.storage.local.set({blocked:s.blocked});}else if(m.type!=='status')throw Error('Unsupported message');return {active:active(s),enabled:s.enabled,config:s.config,usage:s.usage,blocked:s.blocked};}).then(reply).catch(e=>reply({error:e.message}));return true;});
chrome.declarativeNetRequest.onRuleMatchedDebug?.addListener(()=>serial(async()=>{const s=await state();s.blocked++;await chrome.storage.local.set({blocked:s.blocked});}));
