let guard={active:false,config:{}},lastURL='',approved=false,reported='',applying=false;
const style=document.createElement('style');style.id='rebound-feed-style';
function overlay(text){let box=document.getElementById('rebound-block-overlay');if(!box){box=document.createElement('div');box.id='rebound-block-overlay';box.style.cssText='position:fixed;inset:0;z-index:2147483647;background:#f8faf6;color:#123b32;display:grid;place-items:center;font:18px/1.6 system-ui;padding:30px;text-align:center';const inner=document.createElement('div');inner.style.maxWidth='520px';const h=document.createElement('h1');h.textContent='Keep your next step in sight.';const p=document.createElement('p');p.id='rebound-block-reason';const link=document.createElement('a');link.href='https://rebound-school-comeback.astrapro70.chatgpt.site/';link.textContent='Return to Rebound';link.style.cssText='display:inline-block;padding:12px 18px;background:#123b32;color:white;border-radius:8px;text-decoration:none';const back=document.createElement('button');back.textContent='Go back';back.style.cssText='margin-left:15px;padding:12px';back.onclick=()=>history.back();inner.append(h,p,link,back);box.append(inner);document.documentElement.append(box);}if(document.getElementById('rebound-block-reason').textContent!==text)document.getElementById('rebound-block-reason').textContent=text;if(reported!==location.href){reported=location.href;chrome.runtime.sendMessage({type:'feed-block'},()=>void chrome.runtime.lastError);}}
function clear(){document.getElementById('rebound-block-overlay')?.remove();}
function apply(){if(applying)return;applying=true;try{if(!document.documentElement)return;if(!style.isConnected)document.documentElement.append(style);if(lastURL!==location.href){lastURL=location.href;approved=false;clear();}if(!guard.active){if(style.textContent)style.textContent='';approved=true;clear();return;}const youtube=location.hostname.endsWith('youtube.com'),c=guard.config;const css=[];if(youtube){if(c.shorts)css.push('ytd-reel-shelf-renderer,ytd-rich-shelf-renderer[is-shorts],a[href^="/shorts"],ytd-guide-entry-renderer:has(a[title="Shorts"]){display:none!important}');if(c.youtube)css.push('ytd-watch-next-secondary-results-renderer,#related,.ytp-endscreen-content,.ytp-ce-element,ytd-rich-grid-renderer,ytd-browse[page-subtype="home"],ytd-mini-guide-entry-renderer:has(a[title="Shorts"]){display:none!important}');}else if(c.reels)css.push('a[href^="/reels/"],a[href^="/reel/"]{display:none!important}');const nextCSS=css.join('\n');if(style.textContent!==nextCSS)style.textContent=nextCSS;
 let reason='';if(youtube&&c.shorts&&/^\/shorts(?:\/|$)/.test(location.pathname))reason='Shorts are paused during your study session.';else if(!youtube&&c.reels&&/^\/reels?(?:\/|$)/.test(location.pathname))reason='Reels are paused during your study session.';else if(youtube&&c.youtube&&location.pathname==='/watch'){const links=[...document.querySelectorAll('ytd-watch-metadata #owner a[href],ytd-video-owner-renderer a[href]')];const identities=links.map(a=>{try{return new URL(a.href).pathname.replace(/^\/channel\//,'').replace(/^\//,'').split('/')[0];}catch{return '';}});approved=identities.some(x=>c.channels.some(y=>y.startsWith('@')?x.toLowerCase()===y.toLowerCase():x===y));if(!approved)reason=identities.length?'This channel is not on your study allowlist. Use search to find an allowed lecture.':'Checking the lecture channel. Playback stays paused until the channel is allowed.';}else if(youtube&&c.youtube&&location.pathname==='/')reason='Your YouTube home feed is paused. Use YouTube search or open a lecture link.';
 if(reason){document.querySelectorAll('video').forEach(v=>v.pause());overlay(reason);if(youtube&&location.pathname==='/'){const p=document.getElementById('rebound-block-reason');if(!document.getElementById('rebound-youtube-search')){const a=document.createElement('a');a.id='rebound-youtube-search';a.href='https://www.youtube.com/results?search_query=physics+lecture';a.textContent='Open YouTube search';a.style.display='block';p.after(a);}}}else clear();
 }finally{applying=false;}}
function refresh(){chrome.runtime.sendMessage({type:'status'},s=>{if(chrome.runtime.lastError||!s||s.error)return;guard=s;apply();});}
document.addEventListener('play',e=>{if(guard.active&&location.hostname.endsWith('youtube.com')&&guard.config.youtube&&location.pathname==='/watch'&&!approved&&e.target instanceof HTMLMediaElement)e.target.pause();},true);
document.addEventListener('yt-navigate-start',()=>{approved=false;document.querySelectorAll('video').forEach(v=>{if(guard.active&&guard.config.youtube)v.pause();});});
new MutationObserver(()=>{if(!applying)apply();}).observe(document,{childList:true,subtree:true});setInterval(refresh,1000);refresh();
