export const weekdays=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
export const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const defaultSettings=()=>({goal:60,schedules:[],guard:true,breakMinutes:5,breakActivity:'Stretch and look away from the screen',domains:['tiktok.com','reddit.com'],shorts:true,reels:true,youtube:true,channels:[],limits:[],autoBlock:true});
export const minuteOf=t=>{if(!/^\d{2}:\d{2}$/.test(t))throw Error('Use a valid time.');const [h,m]=t.split(':').map(Number);if(h>23||m>59)throw Error('Use a valid time.');return h*60+m;};
export function validateSchedule(value,existing=[]){const s={id:String(value.id||''),subject:String(value.subject||'').trim(),start:value.start,end:value.end,days:[...new Set(value.days||[])].sort()};if(!s.id||s.id.length>80||!s.subject||s.subject.length>40||!s.days.length||s.days.some(d=>!Number.isInteger(d)||d<0||d>6))throw Error('Choose a subject and at least one weekday.');if(minuteOf(s.end)<=minuteOf(s.start))throw Error('End time must be after start time. Split overnight blocks into two blocks.');if(existing.some(x=>x.id!==s.id&&x.days.some(d=>s.days.includes(d))&&minuteOf(x.start)<minuteOf(s.end)&&minuteOf(s.start)<minuteOf(x.end)))throw Error('This overlaps another block on a selected day.');return s;}
export function validateSettings(value){if(!value||typeof value!=='object')throw Error('Invalid settings');const base=defaultSettings();if(!Number.isInteger(value.goal)||value.goal<5||value.goal>720)throw Error('Daily goal must be 5–720 minutes.');if(!Number.isInteger(value.breakMinutes)||value.breakMinutes<1||value.breakMinutes>60)throw Error('Breaks must be 1–60 minutes.');if(!Array.isArray(value.schedules)||value.schedules.length>60)throw Error('Keep at most 60 timetable blocks.');const schedules=[];for(const item of value.schedules){if(schedules.some(x=>x.id===item.id))throw Error('Duplicate timetable ID.');schedules.push(validateSchedule(item,schedules));}const domains=normalizeDomains(value.domains||[]);if(domains.length>60)throw Error('Keep at most 60 blocked domains.');const channels=[...new Set((value.channels||[]).map(String))];if(channels.length>30||channels.some(s=>!/^(@[a-zA-Z0-9_.-]{1,80}|UC[a-zA-Z0-9_-]{22})$/.test(s)))throw Error('Use YouTube @handles or UC channel IDs, one per line.');const limits=(value.limits||[]).map(x=>({domain:normalizeDomains([x.domain])[0],minutes:Number(x.minutes)}));if(limits.length>30||limits.some(x=>!x.domain||!Number.isInteger(x.minutes)||x.minutes<1||x.minutes>720))throw Error('Usage limits must be 1–720 minutes per domain.');return {...base,goal:value.goal,schedules,breakMinutes:value.breakMinutes,breakActivity:String(value.breakActivity||base.breakActivity).slice(0,100),guard:!!value.guard,domains,shorts:!!value.shorts,reels:!!value.reels,youtube:!!value.youtube,channels,limits,autoBlock:!!value.autoBlock};}
export function normalizeDomains(input){return [...new Set(input.map(x=>String(x).trim().toLowerCase()).filter(Boolean).map(x=>{const host=x.replace(/^https?:\/\//,'').split('/')[0];if(!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(host))throw Error('Enter domains such as instagram.com, without ports or wildcards.');if(host==='chatgpt.site'||host.endsWith('.chatgpt.site')||host==='localhost')throw Error('Keep Rebound available during focus.');return host;}))];}
export function elapsedMs(timer,now=Date.now()){if(!timer)return 0;return Math.max(0,Math.min(12*3600000,(timer.accumulated||0)+(timer.running?Math.max(0,now-timer.anchor):0)));}
export function timerRemaining(timer,now=Date.now()){return Math.max(0,timer.duration*1000-elapsedMs(timer,now));}
export function activeSchedule(schedules,now=new Date()){const m=now.getHours()*60+now.getMinutes();return schedules.find(s=>s.days.includes(now.getDay())&&minuteOf(s.start)<=m&&m<minuteOf(s.end))||null;}
export function streakDays(logs,goal,now=new Date()){const totals={};for(const l of logs)if(l.status==='completed'){const day=dateKey(new Date(l.ended));totals[day]=(totals[day]||0)+l.seconds/60;}let d=new Date(now);d.setHours(12,0,0,0);if((totals[dateKey(d)]||0)<goal)d.setDate(d.getDate()-1);let n=0;for(let i=0;i<366;i++){if((totals[dateKey(d)]||0)<goal)break;n++;d.setDate(d.getDate()-1);}return n;}
export function scheduleICS(schedules,now=new Date()){const esc=s=>String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const days=['SU','MO','TU','WE','TH','FR','SA'];const stamp=now.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Rebound//Study schedule//EN','CALSCALE:GREGORIAN'];for(const s of schedules){const d=new Date(now);while(!s.days.includes(d.getDay()))d.setDate(d.getDate()+1);const key=dateKey(d).replace(/-/g,'');lines.push('BEGIN:VEVENT',`UID:${s.id}@rebound`, `DTSTAMP:${stamp}`,`SUMMARY:${esc(s.subject+' study')}`,`DTSTART:${key}T${s.start.replace(':','')}00`,`DTEND:${key}T${s.end.replace(':','')}00`,`RRULE:FREQ=WEEKLY;BYDAY=${s.days.map(x=>days[x]).join(',')}`,'DESCRIPTION:Rebound study block. Times follow your calendar local timezone.','BEGIN:VALARM','TRIGGER:-PT5M','ACTION:DISPLAY','DESCRIPTION:Study block starts in 5 minutes','END:VALARM','END:VEVENT');}lines.push('END:VCALENDAR');return lines.join('\r\n')+'\r\n';}
