import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makePlan,demoState,validateState,plusDays} from '../dist/planner.mjs';
const today='2026-10-02';
test('sample flags impossible deadline and respects all daily limits',()=>{const s=demoState(today),p=makePlan(s,today);assert.equal(p.risks[0].taskId,'demo-bio');assert.equal(p.risks[0].minutes,15);assert.equal(p.scheduled,195);for(const d of p.days){assert.ok(d.used<=d.capacity);assert.ok(d.sessions.every(x=>x.minutes>0&&x.minutes<=25));}assert.equal(p.remaining,p.scheduled+p.risks.reduce((n,r)=>n+r.minutes,0));});
test('rest days never receive work',()=>{const s=demoState(today);s.todayBudget=0;assert.equal(makePlan(s,today).days[0].sessions.length,0);});
test('completion removes exactly completed minutes without refilling consumed time',()=>{const s=demoState(today);const session=makePlan(s,today).days[0].sessions[0];s.tasks.find(t=>t.id===session.taskId).done+=session.minutes;s.todayBudget-=session.minutes;const p=makePlan(s,today);assert.equal(p.days[0].used,20);assert.equal(p.remaining,195);assert.equal(p.risks[0].minutes,15);});
test('overdue work remains flagged even if scheduled today',()=>{const s=demoState(today);s.tasks=[{...s.tasks[0],due:plusDays(today,-1),minutes:20}];const p=makePlan(s,today);assert.equal(p.days[0].used,20);assert.equal(p.risks[0].overdue,true);assert.equal(p.risks[0].minutes,0);});
test('high priority breaks deadline ties',()=>{const s=demoState(today);s.tasks=s.tasks.slice(0,2).map(t=>({...t,due:today}));assert.equal(makePlan(s,today).days[0].sessions[0].taskId,'demo-math');});
test('complete tasks are excluded and future work is distinguished from deadline risk',()=>{const s=demoState(today);s.tasks=[{...s.tasks[0],done:70},{...s.tasks[1],due:plusDays(today,12),minutes:1200}];const p=makePlan(s,today);assert.equal(p.risks.length,1);assert.equal(p.risks[0].beyondHorizon,true);assert.equal(p.remaining,1200);});
test('backup rejects duplicate IDs, invalid dates, negative minutes, and excess progress',()=>{for(const patch of [{due:'2026-02-30'},{minutes:-10},{done:9999},{title:''}]){const s=demoState(today);Object.assign(s.tasks[0],patch);assert.throws(()=>validateState(s));}const s=demoState(today);s.tasks[1].id=s.tasks[0].id;assert.throws(()=>validateState(s));assert.deepEqual(validateState(demoState(today)),demoState(today));});
test('calendar arithmetic crosses months and leap days',()=>{assert.equal(plusDays('2026-12-31',1),'2027-01-01');assert.equal(plusDays('2028-02-28',1),'2028-02-29');});
test('stale today budget resets to daily budget in planner',()=>{const s=demoState('2026-10-01');s.todayBudget=0;assert.equal(makePlan(s,today).days[0].capacity,60);});
test('random workloads conserve time and never exceed capacity or deadline',()=>{let seed=123;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);for(let trial=0;trial<100;trial++){const s=demoState(today);s.budget=Math.floor(random()*121);s.todayBudget=Math.floor(random()*121);s.tasks=Array.from({length:25},(_,i)=>({id:String(i),title:'Task',subject:'Test',due:plusDays(today,Math.floor(random()*12)-2),minutes:5+Math.floor(random()*300),done:0,priority:'normal'}));const p=makePlan(s,today);assert.equal(p.remaining,p.scheduled+p.risks.reduce((n,r)=>n+r.minutes,0));for(const d of p.days){assert.ok(d.used<=d.capacity);for(const x of d.sessions){assert.ok(x.minutes>0&&x.minutes<=25);assert.ok(d.date<=x.due||d.date===today);}}}});

