import {validateSettings,defaultSettings} from '../dist/focus-core.mjs';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const hash=async x=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x))),b=>b.toString(16).padStart(2,'0')).join('');
const modes=['pomodoro','countdown','stopwatch'];
const aliases=['Quiet Otter','Focused Fox','Steady Owl','Curious Panda','Calm Koala','Bright Finch','Patient Penguin','Brave Badger'];
const coachFallback=(prompt,context,logs)=>{const available=Math.max(1,Math.min(720,Number(context?.availableMinutes)||25)),tasks=Array.isArray(context?.tasks)?context.tasks.slice(0,5).map(x=>String(x).trim()).filter(Boolean):[],done=logs.filter(x=>x.status==='completed').length;const first=tasks[0]||'the nearest deadline';if(available<=5)return `Start tiny: spend five minutes opening ${first}, write one question or formula, then stop. A small session still moves your plan forward.`;if(/miss|behind|yesterday/i.test(prompt))return `Life happened. Keep today humane: choose ${first} for ${Math.min(available,25)} minutes, then rebuild the rest after you finish. You already have ${done} saved focus sessions to build on.`;if(/exam|test|quiz/i.test(prompt))return `Use your next ${Math.min(available,30)} minutes on active recall for ${first}: write three questions, answer without notes, then check one gap.`;return `For the next ${Math.min(available,25)} minutes, begin with ${first}. Make the first action visible and small, then take a short non-scrolling break.`;};
const coachContext=x=>({availableMinutes:Number.isInteger(x?.availableMinutes)&&x.availableMinutes>0&&x.availableMinutes<=720?x.availableMinutes:25,tasks:Array.isArray(x?.tasks)?x.tasks.slice(0,8).map(t=>String(t).trim().slice(0,80)).filter(Boolean):[]});
const emptyAcademic=()=>({terms:[],holidays:[],subjects:[],blocks:[],exams:[]});
const isDate=x=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x+'T12:00:00'));
const academicState=input=>{const value=input&&typeof input==='object'?input:emptyAcademic(),cleanText=(x,max)=>String(x||'').trim().slice(0,max),unique=new Set();const list=(name,max,map)=>{if(!Array.isArray(value[name])||value[name].length>max)throw Error(`Keep at most ${max} ${name}.`);return value[name].map(map);};const terms=list('terms',12,x=>{const name=cleanText(x.name,60);if(!name||!isDate(x.start)||!isDate(x.end)||x.start>x.end)throw Error('Each term needs a name and valid date range.');return {id:cleanText(x.id,80)||crypto.randomUUID(),name,start:x.start,end:x.end};});const holidays=list('holidays',80,x=>{const name=cleanText(x.name,60);if(!name||!isDate(x.start)||!isDate(x.end)||x.start>x.end)throw Error('Each holiday needs a name and valid date range.');return {id:cleanText(x.id,80)||crypto.randomUUID(),name,start:x.start,end:x.end};});const subjects=list('subjects',40,x=>{const name=cleanText(x.name,40),color=/^#[0-9a-fA-F]{6}$/.test(x.color)?x.color:'#527bb5';if(!name||unique.has(name.toLowerCase()))throw Error('Subject names must be unique.');unique.add(name.toLowerCase());return {id:cleanText(x.id,80)||crypto.randomUUID(),name,color};});const blocks=list('blocks',120,x=>{const subject=cleanText(x.subject,40),label=cleanText(x.label,60),week=x.week==='B'?'B':'A',day=Number(x.day),start=cleanText(x.start,5),end=cleanText(x.end,5);if(!subject||!label||!Number.isInteger(day)||day<0||day>6||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end)||start>=end)throw Error('Each timetable block needs a subject, day, and valid time.');return {id:cleanText(x.id,80)||crypto.randomUUID(),subject,label,week,day,start,end};});const exams=list('exams',80,x=>{const title=cleanText(x.title,80),subject=cleanText(x.subject,40),date=cleanText(x.date,10);if(!title||!subject||!isDate(date))throw Error('Each exam needs a title, subject, and valid date.');return {id:cleanText(x.id,80)||crypto.randomUUID(),title,subject,date,room:cleanText(x.room,30)};});return {terms,holidays,subjects,blocks,exams};};
export async function api(request,env){try{
 const url=new URL(request.url),path=url.pathname,now=Date.now();
 if(!['GET','POST','PUT','DELETE'].includes(request.method))return json({error:'Unsupported method'},405);
 if(request.method!=='GET'&&request.headers.get('Origin')&&request.headers.get('Origin')!==url.origin)return json({error:'Origin mismatch'},403);
 if(path==='/api/auth-config'&&request.method==='GET'){
  const urlValue=String(env.SUPABASE_URL||'').replace(/\/$/,'');
  const anonKey=String(env.SUPABASE_ANON_KEY||'');
  const enabled=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(urlValue)&&anonKey.length>40;
  return json({enabled,url:enabled?urlValue:null,anonKey:enabled?anonKey:null,providers:{email:enabled,google:enabled}});
 }
 if(!env.DB)return json({error:'Shared storage is unavailable. Your current timer stays on this device.'},503);
 if(Number(request.headers.get('content-length')||0)>100000)return json({error:'Request too large'},413);
 const token=(request.headers.get('Authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token))return json({error:'Missing device credential'},401);const owner=await hash(token);
 const db=env.DB,query=(s,...args)=>db.prepare(s).bind(...args);
 await query('INSERT OR IGNORE INTO focus_profiles (id,created,settings,alias) VALUES (?,?,?,?)',owner,now,JSON.stringify(defaultSettings()),aliases[parseInt(owner.slice(0,2),16)%aliases.length]).run();
 const profile=await query('SELECT * FROM focus_profiles WHERE id=?',owner).first();
 async function body(){const text=await request.text();if(text.length>100000)throw Error('Request too large');return JSON.parse(text);}
 if(path==='/api/state'&&request.method==='GET'){const logs=await query('SELECT id,subject,mode,started,ended,seconds,status,interruptions,room FROM focus_sessions WHERE owner=? AND status != ? ORDER BY started DESC LIMIT 2000',owner,'active').all();return json({settings:JSON.parse(profile.settings),revision:profile.revision,profile:{alias:profile.alias,exam:profile.exam,public:!!profile.public},logs:logs.results});}
 if(path==='/api/coach'&&request.method==='POST'){const b=await body(),prompt=String(b.prompt||'').trim(),context=coachContext(b.context);if(!prompt||prompt.length>400)throw Error('Ask the coach one question of up to 400 characters.');const logs=(await query('SELECT subject,seconds,status,ended FROM focus_sessions WHERE owner=? AND status != ? ORDER BY started DESC LIMIT 40',owner,'active').all()).results;if(!env.FEATHERLESS_API_KEY)return json({reply:coachFallback(prompt,context,logs),provider:'local',notice:'Offline coach mode is active. Add a rotated Featherless server secret to enable AI responses.'});const system='You are Rebound Coach, a warm and concise study-planning helper for ages 13–18. Use only supplied context. Never shame, diagnose, or promise results. Give one realistic next action, a duration, and a gentle reminder to take a break. Keep under 90 words.';const user=`Question: ${prompt}\nAvailable minutes: ${context.availableMinutes}\nTasks the student opted to share: ${context.tasks.join(' | ')||'none'}\nCompleted focus sessions: ${logs.filter(x=>x.status==='completed').length}`;try{const response=await fetch('https://api.featherless.ai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${env.FEATHERLESS_API_KEY}`,'HTTP-Referer':url.origin,'X-Title':'Rebound Coach'},body:JSON.stringify({model:env.FEATHERLESS_MODEL||'Qwen/Qwen2.5-7B-Instruct',messages:[{role:'system',content:system},{role:'user',content:user}],temperature:.4,max_tokens:140})});if(!response.ok)throw Error('Coach service unavailable');const data=await response.json(),reply=String(data?.choices?.[0]?.message?.content||'').trim();if(!reply||reply.length>1200)throw Error('Coach response unavailable');return json({reply,provider:'featherless'});}catch{return json({reply:coachFallback(prompt,context,logs),provider:'local',notice:'The AI coach is temporarily unavailable, so Rebound used its local planning guide.'});}}
 if(path==='/api/academic'&&request.method==='GET'){await query('INSERT OR IGNORE INTO academic_state (owner,state,revision,updated) VALUES (?,?,?,?)',owner,JSON.stringify(emptyAcademic()),0,now).run();const row=await query('SELECT state,revision,updated FROM academic_state WHERE owner=?',owner).first();return json({state:academicState(JSON.parse(row.state)),revision:row.revision,updated:row.updated});}
 if(path==='/api/academic'&&request.method==='PUT'){const b=await body(),state=academicState(b.state);if(!Number.isInteger(b.revision)||b.revision<0)throw Error('Reload academic data before saving.');await query('INSERT OR IGNORE INTO academic_state (owner,state,revision,updated) VALUES (?,?,?,?)',owner,JSON.stringify(emptyAcademic()),0,now).run();const result=await query('UPDATE academic_state SET state=?,revision=revision+1,updated=? WHERE owner=? AND revision=?',JSON.stringify(state),now,owner,b.revision).run();if(!result.meta.changes)return json({error:'Academic data changed in another tab. Reload before saving.'},409);return json({state,revision:b.revision+1,updated:now});}
 if(path==='/api/settings'&&request.method==='PUT'){const b=await body(),settings=validateSettings(b.settings);const result=await query('UPDATE focus_profiles SET settings=?,revision=revision+1 WHERE id=? AND revision=?',JSON.stringify(settings),owner,b.revision).run();if(!result.meta.changes)return json({error:'Settings changed in another tab. Reload before saving.'},409);return json({settings,revision:profile.revision+1});}
 if(path==='/api/profile'&&request.method==='PUT'){const b=await body();if(!aliases.includes(b.alias)||!['General','JEE','NEET','Boards','University'].includes(b.exam)||typeof b.public!=='boolean')throw Error('Choose the supplied alias and exam options.');await query('UPDATE focus_profiles SET alias=?,exam=?,public=? WHERE id=?',b.alias,b.exam,b.public?1:0,owner).run();return json({ok:true});}
 if(path==='/api/sessions/start'&&request.method==='POST'){const b=await body();if(!/^[a-f0-9-]{36}$/.test(b.id)||typeof b.subject!=='string'||!b.subject.trim()||b.subject.length>40||!modes.includes(b.mode)||!Number.isInteger(b.planned)||b.planned<60||b.planned>43200)throw Error('Invalid focus session.');const existing=await query('SELECT owner,started,status FROM focus_sessions WHERE id=?',b.id).first();if(existing){if(existing.owner!==owner)return json({error:'Session unavailable'},403);return json({started:existing.started,status:existing.status});}const recent=await query('SELECT COUNT(*) AS count FROM focus_sessions WHERE owner=? AND started>?',owner,now-86400000).first();if(recent.count>=200)return json({error:'Daily session limit reached.'},429);const active=await query("SELECT id FROM focus_sessions WHERE owner=? AND status='active' AND started>?",owner,now-43200000).first();if(active)return json({error:'A timer is already running on this device. Finish or recover it first.',activeId:active.id},409);let room=null;if(b.room){const joined=await query('SELECT room FROM focus_members WHERE owner=? AND room=?',owner,b.room).first();if(joined)room=b.room;}await query('INSERT INTO focus_sessions (id,owner,subject,mode,started,planned,room) VALUES (?,?,?,?,?,?,?)',b.id,owner,b.subject.trim(),b.mode,now,b.planned,room).run();return json({started:now,status:'active'});}
 if(path==='/api/sessions/finish'&&request.method==='POST'){const b=await body(),s=await query('SELECT * FROM focus_sessions WHERE id=? AND owner=?',b.id,owner).first();if(!s)return json({error:'Session was not found'},404);if(s.status!=='active')return json({session:s});if(!Number.isFinite(b.seconds)||!Number.isInteger(b.interruptions)||b.interruptions<0||b.interruptions>100000||!['completed','aborted'].includes(b.status))throw Error('Invalid session result');const seconds=Math.max(0,Math.floor(Math.min(b.seconds,(now-s.started)/1000,s.planned,43200)));const status=b.status==='completed'&&(s.mode==='stopwatch'?seconds>=1:seconds>=s.planned-2)?'completed':'aborted';await query("UPDATE focus_sessions SET ended=?,seconds=?,status=?,interruptions=? WHERE id=? AND owner=? AND status='active'",now,seconds,status,b.interruptions,b.id,owner).run();return json({session:await query('SELECT * FROM focus_sessions WHERE id=?',b.id).first()});}
 if(path==='/api/sessions/recover'&&request.method==='POST'){await query("UPDATE focus_sessions SET ended=?,status='aborted',seconds=0 WHERE owner=? AND status='active'",now,owner).run();return json({ok:true});}
 if(path==='/api/rooms'&&request.method==='POST'){const recent=await query('SELECT COUNT(*) AS count FROM focus_rooms WHERE owner=? AND created>?',owner,now-86400000).first();if(recent.count>=10)return json({error:'You can create up to 10 rooms a day.'},429);const code=crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase();await db.batch([query('INSERT INTO focus_rooms (code,created,owner) VALUES (?,?,?)',code,now,owner),query('INSERT INTO focus_members (room,owner,last_seen) VALUES (?,?,?)',code,owner,now)]);return json({code});}
 if(path==='/api/rooms/join'&&request.method==='POST'){const b=await body(),code=String(b.code).trim().toUpperCase();if(!/^[A-F0-9]{10}$/.test(code))throw Error('Enter a valid 10-character room code.');const room=await query('SELECT * FROM focus_rooms WHERE code=? AND created>?',code,now-7*86400000).first();if(!room)return json({error:'Room not found or expired after seven days.'},404);const member=await query('SELECT owner FROM focus_members WHERE room=? AND owner=?',code,owner).first();if(!member){const count=await query('SELECT COUNT(*) AS count FROM focus_members WHERE room=?',code).first();if(count.count>=20)return json({error:'This room is full (20 learners).'},409);await query('INSERT INTO focus_members (room,owner,last_seen) VALUES (?,?,?)',code,owner,now).run();}return json({code});}
 if(path.startsWith('/api/rooms/')&&request.method==='GET'){const code=path.split('/').pop();const member=await query('SELECT owner FROM focus_members WHERE room=? AND owner=?',code,owner).first();if(!member)return json({error:'Join this room first.'},403);const room=await query('SELECT created FROM focus_rooms WHERE code=?',code).first();if(!room||room.created<now-7*86400000)return json({error:'Room expired.'},410);await query('UPDATE focus_members SET last_seen=? WHERE room=? AND owner=?',now,code,owner).run();const list=await query("SELECT p.alias,p.exam,m.last_seen,COALESCE(SUM(CASE WHEN s.status='completed' THEN s.seconds ELSE 0 END),0) AS seconds,MAX(CASE WHEN s.status='active' AND s.started>? THEN 1 ELSE 0 END) AS focusing FROM focus_members m JOIN focus_profiles p ON p.id=m.owner LEFT JOIN focus_sessions s ON s.owner=m.owner AND s.room=m.room WHERE m.room=? GROUP BY m.owner ORDER BY seconds DESC",now-43200000,code).all();return json({code,members:list.results.map(x=>({...x,online:x.last_seen>now-60000}))});}
 if(path==='/api/rooms/leave'&&request.method==='POST'){const b=await body();await query('DELETE FROM focus_members WHERE room=? AND owner=?',b.code,owner).run();return json({ok:true});}
 if(path==='/api/leaderboard'&&request.method==='GET'){const exam=url.searchParams.get('exam')||'General';const list=await query("SELECT p.alias,p.exam,SUM(s.seconds) AS seconds FROM focus_profiles p JOIN focus_sessions s ON p.id=s.owner WHERE p.public=1 AND p.exam=? AND s.status='completed' AND s.ended>? GROUP BY p.id ORDER BY seconds DESC LIMIT 30",exam,now-7*86400000).all();return json({entries:list.results});}
 if(path==='/api/account'&&request.method==='DELETE'){await db.batch([query('DELETE FROM focus_members WHERE owner=?',owner),query('DELETE FROM focus_sessions WHERE owner=?',owner),query('DELETE FROM focus_profiles WHERE id=?',owner)]);return json({ok:true});}
 return json({error:'Not found'},404);
}catch(e){if(e instanceof SyntaxError)return json({error:'Invalid JSON'},400);if(/SQLITE|D1_|no such table|database/i.test(e.message)){console.error('Focus storage unavailable',e.message);return json({error:'Focus storage is temporarily unavailable. Try again shortly.'},503);}return json({error:e.message||'Request failed'},400);}}
