import {validateSettings,defaultSettings} from '../dist/focus-core.mjs';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const hash=async x=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x))),b=>b.toString(16).padStart(2,'0')).join('');
const modes=['pomodoro','countdown','stopwatch'];
const aliases=['Quiet Otter','Focused Fox','Steady Owl','Curious Panda','Calm Koala','Bright Finch','Patient Penguin','Brave Badger'];
export async function api(request,env){try{
 if(!env.DB)return json({error:'Shared storage is unavailable. Your current timer stays on this device.'},503);
 const url=new URL(request.url),path=url.pathname,now=Date.now();
 if(!['GET','POST','PUT','DELETE'].includes(request.method))return json({error:'Unsupported method'},405);
 if(request.method!=='GET'&&request.headers.get('Origin')&&request.headers.get('Origin')!==url.origin)return json({error:'Origin mismatch'},403);
 if(Number(request.headers.get('content-length')||0)>100000)return json({error:'Request too large'},413);
 const token=(request.headers.get('Authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token))return json({error:'Missing device credential'},401);const owner=await hash(token);
 const db=env.DB,query=(s,...args)=>db.prepare(s).bind(...args);
 await query('INSERT OR IGNORE INTO focus_profiles (id,created,settings,alias) VALUES (?,?,?,?)',owner,now,JSON.stringify(defaultSettings()),aliases[parseInt(owner.slice(0,2),16)%aliases.length]).run();
 const profile=await query('SELECT * FROM focus_profiles WHERE id=?',owner).first();
 async function body(){const text=await request.text();if(text.length>100000)throw Error('Request too large');return JSON.parse(text);}
 if(path==='/api/state'&&request.method==='GET'){const logs=await query('SELECT id,subject,mode,started,ended,seconds,status,interruptions,room FROM focus_sessions WHERE owner=? AND status != ? ORDER BY started DESC LIMIT 2000',owner,'active').all();return json({settings:JSON.parse(profile.settings),revision:profile.revision,profile:{alias:profile.alias,exam:profile.exam,public:!!profile.public},logs:logs.results});}
 if(path==='/api/settings'&&request.method==='PUT'){const b=await body(),settings=validateSettings(b.settings);const result=await query('UPDATE focus_profiles SET settings=?,revision=revision+1 WHERE id=? AND revision=?',JSON.stringify(settings),owner,b.revision).run();if(!result.meta.changes)return json({error:'Settings changed in another tab. Reload before saving.'},409);return json({settings,revision:profile.revision+1});}
 if(path==='/api/profile'&&request.method==='PUT'){const b=await body();if(!aliases.includes(b.alias)||!['General','JEE','NEET','Boards','University'].includes(b.exam)||typeof b.public!=='boolean')throw Error('Choose the supplied alias and exam options.');await query('UPDATE focus_profiles SET alias=?,exam=?,public=? WHERE id=?',b.alias,b.exam,b.public?1:0,owner).run();return json({ok:true});}
 if(path==='/api/sessions/start'&&request.method==='POST'){const b=await body();if(!/^[a-f0-9-]{36}$/.test(b.id)||typeof b.subject!=='string'||!b.subject.trim()||b.subject.length>40||!modes.includes(b.mode)||!Number.isInteger(b.planned)||b.planned<60||b.planned>43200)throw Error('Invalid focus session.');const existing=await query('SELECT owner,started,status FROM focus_sessions WHERE id=?',b.id).first();if(existing){if(existing.owner!==owner)return json({error:'Session unavailable'},403);return json({started:existing.started,status:existing.status});}const recent=await query('SELECT COUNT(*) AS count FROM focus_sessions WHERE owner=? AND started>?',owner,now-86400000).first();if(recent.count>=200)return json({error:'Daily session limit reached.'},429);const active=await query("SELECT id FROM focus_sessions WHERE owner=? AND status='active' AND started>?",owner,now-43200000).first();if(active)return json({error:'A timer is already running on this device. Finish or recover it first.',activeId:active.id},409);let room=null;if(b.room){const joined=await query('SELECT room FROM focus_members WHERE owner=? AND room=?',owner,b.room).first();if(joined)room=b.room;}await query('INSERT INTO focus_sessions (id,owner,subject,mode,started,planned,room) VALUES (?,?,?,?,?,?,?)',b.id,owner,b.subject.trim(),b.mode,now,b.planned,room).run();return json({started:now,status:'active'});}
 if(path==='/api/sessions/finish'&&request.method==='POST'){const b=await body(),s=await query('SELECT * FROM focus_sessions WHERE id=? AND owner=?',b.id,owner).first();if(!s)return json({error:'Session was not found'},404);if(s.status!=='active')return json({session:s});if(!Number.isFinite(b.seconds)||!Number.isInteger(b.interruptions)||b.interruptions<0||b.interruptions>100000||!['completed','aborted'].includes(b.status))throw Error('Invalid session result');const seconds=Math.max(0,Math.floor(Math.min(b.seconds,(now-s.started)/1000,s.planned,43200)));const status=b.status==='completed'&&(s.mode==='stopwatch'?seconds>=1:seconds>=s.planned-2)?'completed':'aborted';await query("UPDATE focus_sessions SET ended=?,seconds=?,status=?,interruptions=? WHERE id=? AND owner=? AND status='active'",now,seconds,status,b.interruptions,b.id,owner).run();return json({session:await query('SELECT * FROM focus_sessions WHERE id=?',b.id).first()});}
 if(path==='/api/sessions/recover'&&request.method==='POST'){await query("UPDATE focus_sessions SET ended=?,status='aborted',seconds=0 WHERE owner=? AND status='active'",now,owner).run();return json({ok:true});}
 if(path==='/api/rooms'&&request.method==='POST'){const recent=await query('SELECT COUNT(*) AS count FROM focus_rooms WHERE owner=? AND created>?',owner,now-86400000).first();if(recent.count>=10)return json({error:'You can create up to 10 rooms a day.'},429);const code=crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase();await db.batch([query('INSERT INTO focus_rooms (code,created,owner) VALUES (?,?,?)',code,now,owner),query('INSERT INTO focus_members (room,owner,last_seen) VALUES (?,?,?)',code,owner,now)]);return json({code});}
 if(path==='/api/rooms/join'&&request.method==='POST'){const b=await body(),code=String(b.code).trim().toUpperCase();if(!/^[A-F0-9]{10}$/.test(code))throw Error('Enter a valid 10-character room code.');const room=await query('SELECT * FROM focus_rooms WHERE code=? AND created>?',code,now-7*86400000).first();if(!room)return json({error:'Room not found or expired after seven days.'},404);const member=await query('SELECT owner FROM focus_members WHERE room=? AND owner=?',code,owner).first();if(!member){const count=await query('SELECT COUNT(*) AS count FROM focus_members WHERE room=?',code).first();if(count.count>=20)return json({error:'This room is full (20 learners).'},409);await query('INSERT INTO focus_members (room,owner,last_seen) VALUES (?,?,?)',code,owner,now).run();}return json({code});}
 if(path.startsWith('/api/rooms/')&&request.method==='GET'){const code=path.split('/').pop();const member=await query('SELECT owner FROM focus_members WHERE room=? AND owner=?',code,owner).first();if(!member)return json({error:'Join this room first.'},403);const room=await query('SELECT created FROM focus_rooms WHERE code=?',code).first();if(!room||room.created<now-7*86400000)return json({error:'Room expired.'},410);await query('UPDATE focus_members SET last_seen=? WHERE room=? AND owner=?',now,code,owner).run();const list=await query("SELECT p.alias,p.exam,m.last_seen,COALESCE(SUM(CASE WHEN s.status='completed' THEN s.seconds ELSE 0 END),0) AS seconds,MAX(CASE WHEN s.status='active' AND s.started>? THEN 1 ELSE 0 END) AS focusing FROM focus_members m JOIN focus_profiles p ON p.id=m.owner LEFT JOIN focus_sessions s ON s.owner=m.owner AND s.room=m.room WHERE m.room=? GROUP BY m.owner ORDER BY seconds DESC",now-43200000,code).all();return json({code,members:list.results.map(x=>({...x,online:x.last_seen>now-60000}))});}
 if(path==='/api/rooms/leave'&&request.method==='POST'){const b=await body();await query('DELETE FROM focus_members WHERE room=? AND owner=?',b.code,owner).run();return json({ok:true});}
 if(path==='/api/leaderboard'&&request.method==='GET'){const exam=url.searchParams.get('exam')||'General';const list=await query("SELECT p.alias,p.exam,SUM(s.seconds) AS seconds FROM focus_profiles p JOIN focus_sessions s ON p.id=s.owner WHERE p.public=1 AND p.exam=? AND s.status='completed' AND s.ended>? GROUP BY p.id ORDER BY seconds DESC LIMIT 30",exam,now-7*86400000).all();return json({entries:list.results});}
 if(path==='/api/account'&&request.method==='DELETE'){await db.batch([query('DELETE FROM focus_members WHERE owner=?',owner),query('DELETE FROM focus_sessions WHERE owner=?',owner),query('DELETE FROM focus_profiles WHERE id=?',owner)]);return json({ok:true});}
 return json({error:'Not found'},404);
}catch(e){if(e instanceof SyntaxError)return json({error:'Invalid JSON'},400);if(/SQLITE|D1_|no such table|database/i.test(e.message)){console.error('Focus storage unavailable',e.message);return json({error:'Focus storage is temporarily unavailable. Try again shortly.'},503);}return json({error:e.message||'Request failed'},400);}}
